### ISSUE TITLE
Testpoints on interface between ESP32C3 and iCE40UP5k

### ISSUE THREAD

**Issue by emeb** [ICE-V-Wireless/ICE-V-Wireless#2]
When developing new software interfaces on the ESP32C3 it is sometimes helpful to have access to the hardware signals between the ESP32C3 module and iCE40UP5k FPGA. Adding testpoints to the six signals (SPI_PICO, SPI_POCI, SPI_CLK, SPI_CS, CDONE, CRESET) would be helpful. Nothing fancy - just some small pads to solder a wire to or touch with an oscilloscope probe that would be more easily accessible than the QFN pads of the FPGA.

**Comment by mwelling** [comment]
Done!
