### ISSUE TITLE
No PDF of schematic/board design

### ISSUE THREAD

**Issue by twied21** [ICE-V-Wireless/ICE-V-Wireless#20]
There is no easy way to see the full schematic or board design without first needing to download and install kicad and these separate design files. Would like to see a full PDF upload of at least the schematic as reference.
Thanks

**Comment by emeb** [comment]
The schematic is in the docs directory here:
https://github.com/ICE-V-Wireless/ICE-V-Wireless/blob/main/docs/esp32c3_fpga_schematic.pdf
